version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet publish -c release
      - run: apt-get update -y && apt-get install -y sqlite3
      - run: sqlite3 ./examples/todo/todo.db < ./examples/todo/sql/sqlite/schema.sql
      - run: ./bin/release/netcoreapp3.0/linux-x64/publish/dbcore ./examples/todo
      - persist_to_workspace:
          root: ./examples
          paths:
            - todo/*

  test_example_go_api:
    docker:
      - image: golang:1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: ./scripts/post-generate.sh && go build cmd/main.go
          working_directory: ~/todo/api

  test_example_react_browser:
    docker:
      - image: node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: ./scripts/post-generate.sh && yarn build
          working_directory: ~/todo/browser
workflows:
  version: 2
  build:
    jobs:
      - build
      - test_example_go_api:
          requires:
            - build
      - test_example_react_browser:
          requires:
            - build
