version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet publish -c release
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
