version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet publish -c release
      - run: ln -s ./bin/release/netcoreapp3.0/linux-x64/publish/dbcore /usr/local/bin
      - run: dbcore examples/todo
      - persist_to_workspace:
          root: ./examples
          paths:
            - todo/*

  test_example_go_api:
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: go build cmd/main.go
          working_directory: ~/todo/api

  test_example_go_api:
    docker:
      - image: node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: yarn build
          working_directory: ~/todo/browser
workflows:
  version: 2
  build:
    jobs:
      - build
      - test_example_go_api
      - test_example_react_browser
